// Auto-generated by generateContent.js - DO NOT EDIT
// Source: content/weeks.yaml

export interface Session {
  id: number
  title: string
  words: string[]
  type: 'syllable_count' | 'first_syllable' | 'build_word' | 'fusion' | 'mixed'
}

export interface Week {
  id: number
  title: string
  badge: {
    name: string
    icon: string
  }
  sessions: Session[]
}

export type WeeksProgram = Week[]

export const WEEKS_PROGRAM: WeeksProgram = [
  {
    "id": 1,
    "title": "Découverte des sons",
    "badge": {
      "name": "Explorateur des sons",
      "icon": "🔊"
    },
    "sessions": [
      {
        "id": 1,
        "title": "Écoute et compte",
        "words": [
          "papa",
          "mama",
          "bébé",
          "dodo"
        ],
        "type": "syllable_count"
      },
      {
        "id": 2,
        "title": "Trouve la première",
        "words": [
          "toto",
          "lolo",
          "mimi",
          "fifi"
        ],
        "type": "first_syllable"
      },
      {
        "id": 3,
        "title": "Construis les mots",
        "words": [
          "nana",
          "dada",
          "riri",
          "vélo"
        ],
        "type": "build_word"
      },
      {
        "id": 4,
        "title": "Évaluation",
        "words": [
          "papa",
          "mama",
          "toto",
          "vélo"
        ],
        "type": "mixed"
      }
    ]
  },
  {
    "id": 2,
    "title": "Chasseur de syllabes",
    "badge": {
      "name": "Détective de syllabes",
      "icon": "🔍"
    },
    "sessions": [
      {
        "id": 1,
        "title": "Robot parleur",
        "words": [
          "photo",
          "moto",
          "solo",
          "lama"
        ],
        "type": "fusion"
      },
      {
        "id": 2,
        "title": "Compte et construis",
        "words": [
          "tomate",
          "salade",
          "robot",
          "lavabo"
        ],
        "type": "mixed"
      },
      {
        "id": 3,
        "title": "Chasse aux syllabes",
        "words": [
          "bateau",
          "soleil",
          "malade",
          "domino"
        ],
        "type": "first_syllable"
      },
      {
        "id": 4,
        "title": "Évaluation",
        "words": [
          "tomate",
          "robot",
          "photo",
          "lavabo"
        ],
        "type": "mixed"
      }
    ]
  },
  {
    "id": 3,
    "title": "Construction de mots",
    "badge": {
      "name": "Architecte de mots",
      "icon": "🏗️"
    },
    "sessions": [
      {
        "id": 1,
        "title": "Grands mots",
        "words": [
          "banane",
          "citron",
          "melon",
          "salon"
        ],
        "type": "syllable_count"
      },
      {
        "id": 2,
        "title": "Trouve et construis",
        "words": [
          "radis",
          "limonade",
          "carotte",
          "cerise"
        ],
        "type": "mixed"
      },
      {
        "id": 3,
        "title": "Robot avancé",
        "words": [
          "orange",
          "limace",
          "tulipe",
          "pilote"
        ],
        "type": "fusion"
      },
      {
        "id": 4,
        "title": "Évaluation",
        "words": [
          "banane",
          "carotte",
          "orange",
          "tulipe"
        ],
        "type": "mixed"
      }
    ]
  },
  {
    "id": 4,
    "title": "Maîtrise niveau 1",
    "badge": {
      "name": "Champion du mois 1",
      "icon": "🏆"
    },
    "sessions": [
      {
        "id": 1,
        "title": "Défis variés",
        "words": [
          "pirate",
          "girafe",
          "tortue",
          "fenêtre"
        ],
        "type": "mixed"
      },
      {
        "id": 2,
        "title": "Grands défis",
        "words": [
          "numéro",
          "pantalon",
          "caméra",
          "cinéma"
        ],
        "type": "mixed"
      },
      {
        "id": 3,
        "title": "Révisions",
        "words": [
          "animal",
          "ballon",
          "biberon",
          "camion"
        ],
        "type": "mixed"
      },
      {
        "id": 4,
        "title": "Évaluation finale",
        "words": [
          "pirate",
          "pantalon",
          "animal",
          "camion"
        ],
        "type": "mixed"
      }
    ]
  }
]
