// Auto-generated by generateContent.js - DO NOT EDIT
// Source: content/weeks.yaml

export interface WordData {
  syllables: string[]
  count: number
  category: string
  week: number
  emoji: string
}

export type WordsDatabase = Record<string, WordData>

export const WORDS_DATABASE: WordsDatabase = {
  "papa": {
    "syllables": [
      "pa",
      "pa"
    ],
    "count": 2,
    "category": "famille",
    "week": 1,
    "emoji": "👨"
  },
  "mama": {
    "syllables": [
      "ma",
      "ma"
    ],
    "count": 2,
    "category": "famille",
    "week": 1,
    "emoji": "👩"
  },
  "bébé": {
    "syllables": [
      "bé",
      "bé"
    ],
    "count": 2,
    "category": "famille",
    "week": 1,
    "emoji": "👶"
  },
  "dodo": {
    "syllables": [
      "do",
      "do"
    ],
    "count": 2,
    "category": "actions",
    "week": 1,
    "emoji": "😴"
  },
  "toto": {
    "syllables": [
      "to",
      "to"
    ],
    "count": 2,
    "category": "prenom",
    "week": 1,
    "emoji": "👦"
  },
  "lolo": {
    "syllables": [
      "lo",
      "lo"
    ],
    "count": 2,
    "category": "prenom",
    "week": 1,
    "emoji": "🧒"
  },
  "mimi": {
    "syllables": [
      "mi",
      "mi"
    ],
    "count": 2,
    "category": "prenom",
    "week": 1,
    "emoji": "👧"
  },
  "fifi": {
    "syllables": [
      "fi",
      "fi"
    ],
    "count": 2,
    "category": "prenom",
    "week": 1,
    "emoji": "🧑"
  },
  "nana": {
    "syllables": [
      "na",
      "na"
    ],
    "count": 2,
    "category": "prenom",
    "week": 1,
    "emoji": "👱"
  },
  "dada": {
    "syllables": [
      "da",
      "da"
    ],
    "count": 2,
    "category": "animaux",
    "week": 1,
    "emoji": "🐴"
  },
  "riri": {
    "syllables": [
      "ri",
      "ri"
    ],
    "count": 2,
    "category": "prenom",
    "week": 1,
    "emoji": "🧒"
  },
  "vélo": {
    "syllables": [
      "vé",
      "lo"
    ],
    "count": 2,
    "category": "transport",
    "week": 1,
    "emoji": "🚲"
  },
  "photo": {
    "syllables": [
      "pho",
      "to"
    ],
    "count": 2,
    "category": "objets",
    "week": 2,
    "emoji": "📷"
  },
  "moto": {
    "syllables": [
      "mo",
      "to"
    ],
    "count": 2,
    "category": "transport",
    "week": 2,
    "emoji": "🏍️"
  },
  "solo": {
    "syllables": [
      "so",
      "lo"
    ],
    "count": 2,
    "category": "musique",
    "week": 2,
    "emoji": "🎵"
  },
  "lama": {
    "syllables": [
      "la",
      "ma"
    ],
    "count": 2,
    "category": "animaux",
    "week": 2,
    "emoji": "🦙"
  },
  "tomate": {
    "syllables": [
      "to",
      "ma",
      "te"
    ],
    "count": 3,
    "category": "nourriture",
    "week": 2,
    "emoji": "🍅"
  },
  "salade": {
    "syllables": [
      "sa",
      "la",
      "de"
    ],
    "count": 3,
    "category": "nourriture",
    "week": 2,
    "emoji": "🥗"
  },
  "robot": {
    "syllables": [
      "ro",
      "bot"
    ],
    "count": 2,
    "category": "jouets",
    "week": 2,
    "emoji": "🤖"
  },
  "lavabo": {
    "syllables": [
      "la",
      "va",
      "bo"
    ],
    "count": 3,
    "category": "maison",
    "week": 2,
    "emoji": "🚰"
  },
  "bateau": {
    "syllables": [
      "ba",
      "teau"
    ],
    "count": 2,
    "category": "transport",
    "week": 2,
    "emoji": "⛵"
  },
  "soleil": {
    "syllables": [
      "so",
      "leil"
    ],
    "count": 2,
    "category": "nature",
    "week": 2,
    "emoji": "☀️"
  },
  "malade": {
    "syllables": [
      "ma",
      "la",
      "de"
    ],
    "count": 3,
    "category": "etats",
    "week": 2,
    "emoji": "🤒"
  },
  "domino": {
    "syllables": [
      "do",
      "mi",
      "no"
    ],
    "count": 3,
    "category": "jeux",
    "week": 2,
    "emoji": "🎲"
  },
  "banane": {
    "syllables": [
      "ba",
      "na",
      "ne"
    ],
    "count": 3,
    "category": "nourriture",
    "week": 3,
    "emoji": "🍌"
  },
  "citron": {
    "syllables": [
      "ci",
      "tron"
    ],
    "count": 2,
    "category": "nourriture",
    "week": 3,
    "emoji": "🍋"
  },
  "melon": {
    "syllables": [
      "me",
      "lon"
    ],
    "count": 2,
    "category": "nourriture",
    "week": 3,
    "emoji": "🍈"
  },
  "salon": {
    "syllables": [
      "sa",
      "lon"
    ],
    "count": 2,
    "category": "maison",
    "week": 3,
    "emoji": "🛋️"
  },
  "radis": {
    "syllables": [
      "ra",
      "dis"
    ],
    "count": 2,
    "category": "nourriture",
    "week": 3,
    "emoji": "🌰"
  },
  "limonade": {
    "syllables": [
      "li",
      "mo",
      "na",
      "de"
    ],
    "count": 4,
    "category": "nourriture",
    "week": 3,
    "emoji": "🍋"
  },
  "carotte": {
    "syllables": [
      "ca",
      "ro",
      "tte"
    ],
    "count": 3,
    "category": "nourriture",
    "week": 3,
    "emoji": "🥕"
  },
  "cerise": {
    "syllables": [
      "ce",
      "ri",
      "se"
    ],
    "count": 3,
    "category": "nourriture",
    "week": 3,
    "emoji": "🍒"
  },
  "orange": {
    "syllables": [
      "o",
      "ran",
      "ge"
    ],
    "count": 3,
    "category": "nourriture",
    "week": 3,
    "emoji": "🍊"
  },
  "limace": {
    "syllables": [
      "li",
      "ma",
      "ce"
    ],
    "count": 3,
    "category": "animaux",
    "week": 3,
    "emoji": "🐌"
  },
  "tulipe": {
    "syllables": [
      "tu",
      "li",
      "pe"
    ],
    "count": 3,
    "category": "nature",
    "week": 3,
    "emoji": "🌷"
  },
  "pilote": {
    "syllables": [
      "pi",
      "lo",
      "te"
    ],
    "count": 3,
    "category": "metiers",
    "week": 3,
    "emoji": "🧑‍✈️"
  },
  "pirate": {
    "syllables": [
      "pi",
      "ra",
      "te"
    ],
    "count": 3,
    "category": "metiers",
    "week": 4,
    "emoji": "🏴‍☠️"
  },
  "girafe": {
    "syllables": [
      "gi",
      "ra",
      "fe"
    ],
    "count": 3,
    "category": "animaux",
    "week": 4,
    "emoji": "🦒"
  },
  "tortue": {
    "syllables": [
      "tor",
      "tue"
    ],
    "count": 2,
    "category": "animaux",
    "week": 4,
    "emoji": "🐢"
  },
  "fenêtre": {
    "syllables": [
      "fe",
      "nê",
      "tre"
    ],
    "count": 3,
    "category": "maison",
    "week": 4,
    "emoji": "🪟"
  },
  "numéro": {
    "syllables": [
      "nu",
      "mé",
      "ro"
    ],
    "count": 3,
    "category": "nombres",
    "week": 4,
    "emoji": "🔢"
  },
  "pantalon": {
    "syllables": [
      "pan",
      "ta",
      "lon"
    ],
    "count": 3,
    "category": "vetements",
    "week": 4,
    "emoji": "👖"
  },
  "caméra": {
    "syllables": [
      "ca",
      "mé",
      "ra"
    ],
    "count": 3,
    "category": "objets",
    "week": 4,
    "emoji": "📹"
  },
  "cinéma": {
    "syllables": [
      "ci",
      "né",
      "ma"
    ],
    "count": 3,
    "category": "loisirs",
    "week": 4,
    "emoji": "🎬"
  },
  "animal": {
    "syllables": [
      "a",
      "ni",
      "mal"
    ],
    "count": 3,
    "category": "animaux",
    "week": 4,
    "emoji": "🐾"
  },
  "ballon": {
    "syllables": [
      "ba",
      "llon"
    ],
    "count": 2,
    "category": "jouets",
    "week": 4,
    "emoji": "🎈"
  },
  "biberon": {
    "syllables": [
      "bi",
      "be",
      "ron"
    ],
    "count": 3,
    "category": "bebe",
    "week": 4,
    "emoji": "🍼"
  },
  "camion": {
    "syllables": [
      "ca",
      "mion"
    ],
    "count": 2,
    "category": "transport",
    "week": 4,
    "emoji": "🚚"
  }
}
